### ISSUE TITLE
Public Release Checklist

### ISSUE THREAD

**Issue by lgeorge-idm** [InstituteforDiseaseModeling/synthpops#20]
- [x] Tag the first release version (@lgeorge-idm )
- [x] Convert the repo to public (@lgeorge-idm)
- [x] Push released version to PyPi (@cliffckerr )
